version: '2'
volumes:
    krb5kdc-data:

services:
   kdc:
     image: gcavalcante8808/krb5-server
     restart: always
     ports:
      - "88:88"
      - "464:464"
      - "749:749"
     environment:
       KRB5_REALM: EXAMPLE.COM
       KRB5_KDC: localhost
     volumes:
      - krb5kdc-data:/var/lib/krb5kdc
